# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true

os:
  - linux
  - osx

r:
  - 3.4
  - 3.5
#  - oldrel
  - release
#  - devel

bioc_required: true
bioc_use_devel: true

# Workaround for vignette
r_packages:
  - rjson

bioc_packages:
  - DESeq2
  - tximport
  - fgsea

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
